<#
.SYNOPSIS
    Consolidates PKI assessment and health reports from multiple CA servers into a single Excel workbook.

.DESCRIPTION
    This script processes PKI assessment data from multiple Certificate Authority servers
    and combines all information into a comprehensive Excel workbook with multiple worksheets:
    
    Assessment Data (from PKI_Assessment folders):
    - Issued Certificates (all CAs combined)
    - Certificate Templates (all CAs combined)
    - Template Permissions (all CAs combined)
    - Certificate Summary by CA
    
    Health Data (from PKI_Health folders):
    - Health Summary (all CAs)
    - CRL Distribution Health
    - AIA Distribution Health
    - Template Health Status
    - Event Log Issues
    
    The script automatically discovers all CA assessment folders and processes the most recent
    assessment from each CA server.

.PARAMETER AssessmentPath
    Path to the directory containing PKI_Assessment folders from multiple CAs.
    Default: C:\Reports\PKI_Assessment

.PARAMETER HealthPath
    Path to the directory containing PKI_Health folders from multiple CAs.
    Default: C:\Reports\PKI_Health

.PARAMETER OutputDirectory
    Directory where the consolidated Excel file will be saved.
    Default: C:\Reports\PKI_Consolidated

.PARAMETER OutputFileName
    Name for the output Excel file (without extension).
    Default: PKI_Consolidated_Assessment_{timestamp}.xlsx

.PARAMETER OrganizationName
    Organization name for the report.
    Default: Organization

.EXAMPLE
    .\Merge-PKIAssessmentReports.ps1
    
    Processes all PKI assessments and health reports from default locations.

.EXAMPLE
    .\Merge-PKIAssessmentReports.ps1 -AssessmentPath "D:\PKI\Assessment" -HealthPath "D:\PKI\Health"
    
    Processes reports from custom directories.

.EXAMPLE
    .\Merge-PKIAssessmentReports.ps1 -OutputDirectory "D:\Reports" -OrganizationName "Contoso"
    
    Saves consolidated report to custom location with organization name.

.NOTES
    Author: W. Ford
    Date: 2025-12-24
    Version: 1.0
    
    Requirements:
    - PowerShell 5.1 or later
    - ImportExcel module (will attempt to install if missing)
    - Read access to PKI assessment and health folders
    
    This script processes data generated by:
    - Get-ComprehensivePKIReport.ps1
    - Get-PKIHealthReport.ps1

.LINK
    https://github.com/dfinke/ImportExcel
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false, HelpMessage="Path to PKI_Assessment folders")]
    [string]$AssessmentPath = "C:\Reports\PKI_Assessment",
    
    [Parameter(Mandatory=$false, HelpMessage="Path to PKI_Health folders")]
    [string]$HealthPath = "C:\Reports\PKI_Health",
    
    [Parameter(Mandatory=$false, HelpMessage="Output directory for consolidated report")]
    [string]$OutputDirectory = "C:\Reports\PKI_Consolidated",
    
    [Parameter(Mandatory=$false, HelpMessage="Output file name (without extension)")]
    [string]$OutputFileName = "",
    
    [Parameter(Mandatory=$false, HelpMessage="Organization name for reports")]
    [string]$OrganizationName = "Organization"
)

#Requires -Version 5.1

# ============================================================================
# INITIALIZATION
# ============================================================================

$StartTime = Get-Date
$Separator = "=" * 80

Write-Host "`n$Separator" -ForegroundColor Cyan
Write-Host "$OrganizationName - PKI REPORT CONSOLIDATION" -ForegroundColor Cyan
Write-Host "Started: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
Write-Host $Separator -ForegroundColor Cyan

# Check for ImportExcel module
Write-Host "`nChecking for ImportExcel module..." -ForegroundColor Cyan
if (-not (Get-Module -Name ImportExcel -ListAvailable)) {
    Write-Host "⚠️  ImportExcel module not found - attempting installation..." -ForegroundColor Yellow
    try {
        Install-Module -Name ImportExcel -Scope CurrentUser -Force -AllowClobber -ErrorAction Stop
        Write-Host "✅ ImportExcel module installed successfully" -ForegroundColor Green
    }
    catch {
        Write-Host "❌ Failed to install ImportExcel module: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "   Install manually with: Install-Module ImportExcel -Scope CurrentUser" -ForegroundColor Yellow
        exit 1
    }
}

try {
    Import-Module ImportExcel -ErrorAction Stop
    Write-Host "✅ ImportExcel module loaded" -ForegroundColor Green
}
catch {
    Write-Host "❌ Failed to load ImportExcel module: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# Validate input paths
if (-not (Test-Path $AssessmentPath)) {
    Write-Host "❌ Assessment path not found: $AssessmentPath" -ForegroundColor Red
    Write-Host "   Ensure PKI assessment reports have been generated" -ForegroundColor Yellow
    exit 1
}

$healthPathExists = Test-Path $HealthPath
if (-not $healthPathExists) {
    Write-Host "⚠️  Health path not found: $HealthPath" -ForegroundColor Yellow
    Write-Host "   Health data will not be included in the consolidated report" -ForegroundColor Yellow
}

# Create output directory
if (!(Test-Path $OutputDirectory)) {
    try {
        New-Item -ItemType Directory -Path $OutputDirectory -Force -ErrorAction Stop | Out-Null
        Write-Host "✅ Created output directory: $OutputDirectory" -ForegroundColor Green
    }
    catch {
        Write-Host "❌ Cannot create output directory: $($_.Exception.Message)" -ForegroundColor Red
        exit 1
    }
}

# Set output file name
$Timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
if ([string]::IsNullOrWhiteSpace($OutputFileName)) {
    $OutputFileName = "PKI_Consolidated_Assessment_$Timestamp"
}
$OutputFile = Join-Path $OutputDirectory "$OutputFileName.xlsx"

Write-Host "`nOutput file: $OutputFile" -ForegroundColor Cyan

# ============================================================================
# DISCOVER ASSESSMENT FOLDERS
# ============================================================================

Write-Host "`n$Separator" -ForegroundColor Cyan
Write-Host "Discovering Assessment Data" -ForegroundColor Cyan
Write-Host $Separator -ForegroundColor Cyan

# Find all CA assessment folders
$assessmentFolders = Get-ChildItem -Path $AssessmentPath -Directory -Filter "*_PKI_Assessment_*" -ErrorAction SilentlyContinue

if (-not $assessmentFolders -or $assessmentFolders.Count -eq 0) {
    Write-Host "❌ No PKI assessment folders found in: $AssessmentPath" -ForegroundColor Red
    Write-Host "   Expected folder pattern: SERVERNAME_PKI_Assessment_YYYYMMDD_HHMMSS" -ForegroundColor Yellow
    exit 1
}

Write-Host "✅ Found $($assessmentFolders.Count) assessment folder(s)" -ForegroundColor Green

# Group by CA server name (extract from folder name)
$caAssessments = @{}
foreach ($folder in $assessmentFolders) {
    # Extract CA name from folder name (e.g., "LAX11CA01_PKI_Assessment_20251224_154224")
    if ($folder.Name -match '^(.+?)_PKI_Assessment_(\d{8}_\d{6})$') {
        $caName = $Matches[1]
        $timestamp = $Matches[2]
        
        if (-not $caAssessments.ContainsKey($caName)) {
            $caAssessments[$caName] = @()
        }
        
        $caAssessments[$caName] += @{
            CAName = $caName
            Timestamp = $timestamp
            FolderPath = $folder.FullName
            FolderName = $folder.Name
        }
    }
}

# Get most recent assessment for each CA
$latestAssessments = @{}
foreach ($ca in $caAssessments.Keys) {
    $latest = $caAssessments[$ca] | Sort-Object Timestamp -Descending | Select-Object -First 1
    $latestAssessments[$ca] = $latest
    Write-Host "   $ca - Latest: $($latest.Timestamp)" -ForegroundColor White
}

# ============================================================================
# DISCOVER HEALTH FOLDERS
# ============================================================================

$latestHealthReports = @{}

if ($healthPathExists) {
    Write-Host "`n$Separator" -ForegroundColor Cyan
    Write-Host "Discovering Health Data" -ForegroundColor Cyan
    Write-Host $Separator -ForegroundColor Cyan
    
    $healthFolders = Get-ChildItem -Path $HealthPath -Directory -Filter "*_PKI_Health_*" -ErrorAction SilentlyContinue
    
    if ($healthFolders -and $healthFolders.Count -gt 0) {
        Write-Host "✅ Found $($healthFolders.Count) health folder(s)" -ForegroundColor Green
        
        # Group by CA server name
        $caHealth = @{}
        foreach ($folder in $healthFolders) {
            if ($folder.Name -match '^(.+?)_PKI_Health_(\d{8}_\d{6})$') {
                $caName = $Matches[1]
                $timestamp = $Matches[2]
                
                if (-not $caHealth.ContainsKey($caName)) {
                    $caHealth[$caName] = @()
                }
                
                $caHealth[$caName] += @{
                    CAName = $caName
                    Timestamp = $timestamp
                    FolderPath = $folder.FullName
                    FolderName = $folder.Name
                }
            }
        }
        
        # Get most recent health report for each CA
        foreach ($ca in $caHealth.Keys) {
            $latest = $caHealth[$ca] | Sort-Object Timestamp -Descending | Select-Object -First 1
            $latestHealthReports[$ca] = $latest
            Write-Host "   $ca - Latest: $($latest.Timestamp)" -ForegroundColor White
        }
    }
    else {
        Write-Host "⚠️  No PKI health folders found in: $HealthPath" -ForegroundColor Yellow
    }
}

# ============================================================================
# LOAD ASSESSMENT DATA
# ============================================================================

Write-Host "`n$Separator" -ForegroundColor Cyan
Write-Host "Loading Assessment Data" -ForegroundColor Cyan
Write-Host $Separator -ForegroundColor Cyan

$allCertificates = @()
$allTemplates = @()
$allPermissions = @()
$caSummary = @()

foreach ($ca in $latestAssessments.Keys) {
    $assessment = $latestAssessments[$ca]
    Write-Host "`nProcessing: $($assessment.CAName)" -ForegroundColor Cyan
    
    # Load certificates
    $certFile = Join-Path $assessment.FolderPath "$($assessment.CAName)_PKI_IssuedCertificates_$($assessment.Timestamp).csv"
    if (Test-Path $certFile) {
        try {
            $certs = Import-Csv -Path $certFile -ErrorAction Stop
            
            # Add CA name to each record
            $certs | ForEach-Object {
                $_ | Add-Member -NotePropertyName "CAServer" -NotePropertyValue $assessment.CAName -Force
            }
            
            $allCertificates += $certs
            Write-Host "   ✅ Loaded $($certs.Count) certificates" -ForegroundColor Green
            
            # Calculate summary stats
            $issued = ($certs | Where-Object { $_.ExpirationStatus -eq 'Valid' }).Count
            $expiring = ($certs | Where-Object { $_.ExpirationStatus -eq 'Expiring Soon' }).Count
            $expired = ($certs | Where-Object { $_.ExpirationStatus -eq 'Expired' }).Count
            
            $caSummary += [PSCustomObject]@{
                CAServer = $assessment.CAName
                TotalCertificates = $certs.Count
                ValidCertificates = $issued
                ExpiringSoon = $expiring
                Expired = $expired
                AssessmentDate = $assessment.Timestamp
            }
        }
        catch {
            Write-Host "   ⚠️  Failed to load certificates: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
    else {
        Write-Host "   ⚠️  Certificate file not found: $certFile" -ForegroundColor Yellow
    }
    
    # Load templates
    $templateFile = Join-Path $assessment.FolderPath "$($assessment.CAName)_PKI_CertificateTemplates_$($assessment.Timestamp).csv"
    if (Test-Path $templateFile) {
        try {
            $templates = Import-Csv -Path $templateFile -ErrorAction Stop
            
            # Add CA name to each record
            $templates | ForEach-Object {
                $_ | Add-Member -NotePropertyName "CAServer" -NotePropertyValue $assessment.CAName -Force
            }
            
            $allTemplates += $templates
            Write-Host "   ✅ Loaded $($templates.Count) certificate templates" -ForegroundColor Green
        }
        catch {
            Write-Host "   ⚠️  Failed to load templates: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
    else {
        Write-Host "   ⚠️  Template file not found: $templateFile" -ForegroundColor Yellow
    }
    
    # Load permissions
    $permFile = Join-Path $assessment.FolderPath "$($assessment.CAName)_PKI_TemplatePermissions_$($assessment.Timestamp).csv"
    if (Test-Path $permFile) {
        try {
            $perms = Import-Csv -Path $permFile -ErrorAction Stop
            
            # Add CA name to each record
            $perms | ForEach-Object {
                $_ | Add-Member -NotePropertyName "CAServer" -NotePropertyValue $assessment.CAName -Force
            }
            
            $allPermissions += $perms
            Write-Host "   ✅ Loaded $($perms.Count) permission entries" -ForegroundColor Green
        }
        catch {
            Write-Host "   ⚠️  Failed to load permissions: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
    else {
        Write-Host "   ⚠️  Permission file not found: $permFile" -ForegroundColor Yellow
    }
}

Write-Host "`nAssessment Data Summary:" -ForegroundColor Cyan
Write-Host "   Total Certificates: $($allCertificates.Count)" -ForegroundColor White
Write-Host "   Total Templates: $($allTemplates.Count)" -ForegroundColor White
Write-Host "   Total Permission Entries: $($allPermissions.Count)" -ForegroundColor White

# ============================================================================
# LOAD HEALTH DATA
# ============================================================================

$allHealthSummary = @()
$allCRLHealth = @()
$allAIAHealth = @()
$allTemplateHealth = @()
$allEventLogIssues = @()

if ($latestHealthReports.Count -gt 0) {
    Write-Host "`n$Separator" -ForegroundColor Cyan
    Write-Host "Loading Health Data" -ForegroundColor Cyan
    Write-Host $Separator -ForegroundColor Cyan
    
    foreach ($ca in $latestHealthReports.Keys) {
        $health = $latestHealthReports[$ca]
        Write-Host "`nProcessing: $($health.CAName)" -ForegroundColor Cyan
        
        # Parse health report text file for summary data
        $reportFile = Join-Path $health.FolderPath "$($health.CAName)_PKI_Health_Report_$($health.Timestamp).txt"
        if (Test-Path $reportFile) {
            try {
                $reportContent = Get-Content -Path $reportFile -Raw -ErrorAction Stop
                
                # Extract key metrics using regex
                $healthScore = if ($reportContent -match 'Health Score:\s*(\d+)/100') { $Matches[1] } else { 'N/A' }
                $healthStatus = if ($reportContent -match 'Status:\s*(\w+)') { $Matches[1] } else { 'N/A' }
                $errors = if ($reportContent -match 'Errors:\s*(\d+)') { $Matches[1] } else { '0' }
                $warnings = if ($reportContent -match 'Warnings:\s*(\d+)') { $Matches[1] } else { '0' }
                $serviceStatus = if ($reportContent -match 'Service Status:\s*(\w+)') { $Matches[1] } else { 'Unknown' }
                $daysUntilExpiration = if ($reportContent -match 'Days Until Expiration:\s*(\d+)') { $Matches[1] } else { 'N/A' }
                $dbSizeMB = if ($reportContent -match 'Database Size:\s*([\d.]+)\s*MB') { $Matches[1] } else { 'N/A' }
                $totalRecords = if ($reportContent -match 'Total Records:\s*(\d+)') { $Matches[1] } else { 'N/A' }
                
                $allHealthSummary += [PSCustomObject]@{
                    CAServer = $health.CAName
                    HealthScore = $healthScore
                    Status = $healthStatus
                    Errors = $errors
                    Warnings = $warnings
                    ServiceStatus = $serviceStatus
                    CACertDaysUntilExpiration = $daysUntilExpiration
                    DatabaseSizeMB = $dbSizeMB
                    TotalDatabaseRecords = $totalRecords
                    AssessmentDate = $health.Timestamp
                }
                
                Write-Host "   ✅ Parsed health report (Score: $healthScore/100)" -ForegroundColor Green
            }
            catch {
                Write-Host "   ⚠️  Failed to parse health report: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
        
        # Load CRL health
        $crlFile = Join-Path $health.FolderPath "$($health.CAName)_PKI_CRLHealth_$($health.Timestamp).csv"
        if (Test-Path $crlFile) {
            try {
                $crls = Import-Csv -Path $crlFile -ErrorAction Stop
                $crls | ForEach-Object {
                    $_ | Add-Member -NotePropertyName "CAServer" -NotePropertyValue $health.CAName -Force
                }
                $allCRLHealth += $crls
                Write-Host "   ✅ Loaded $($crls.Count) CRL health entries" -ForegroundColor Green
            }
            catch {
                Write-Host "   ⚠️  Failed to load CRL health: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
        
        # Load AIA health
        $aiaFile = Join-Path $health.FolderPath "$($health.CAName)_PKI_AIAHealth_$($health.Timestamp).csv"
        if (Test-Path $aiaFile) {
            try {
                $aias = Import-Csv -Path $aiaFile -ErrorAction Stop
                $aias | ForEach-Object {
                    $_ | Add-Member -NotePropertyName "CAServer" -NotePropertyValue $health.CAName -Force
                }
                $allAIAHealth += $aias
                Write-Host "   ✅ Loaded $($aias.Count) AIA health entries" -ForegroundColor Green
            }
            catch {
                Write-Host "   ⚠️  Failed to load AIA health: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
        
        # Load template health
        $tempHealthFile = Join-Path $health.FolderPath "$($health.CAName)_PKI_TemplateHealth_$($health.Timestamp).csv"
        if (Test-Path $tempHealthFile) {
            try {
                $tempHealth = Import-Csv -Path $tempHealthFile -ErrorAction Stop
                $tempHealth | ForEach-Object {
                    $_ | Add-Member -NotePropertyName "CAServer" -NotePropertyValue $health.CAName -Force
                }
                $allTemplateHealth += $tempHealth
                Write-Host "   ✅ Loaded $($tempHealth.Count) template health entries" -ForegroundColor Green
            }
            catch {
                Write-Host "   ⚠️  Failed to load template health: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
        
        # Load event log issues
        $eventsFile = Join-Path $health.FolderPath "$($health.CAName)_PKI_EventLogIssues_$($health.Timestamp).csv"
        if (Test-Path $eventsFile) {
            try {
                $events = Import-Csv -Path $eventsFile -ErrorAction Stop
                $events | ForEach-Object {
                    $_ | Add-Member -NotePropertyName "CAServer" -NotePropertyValue $health.CAName -Force
                }
                $allEventLogIssues += $events
                Write-Host "   ✅ Loaded $($events.Count) event log issues" -ForegroundColor Green
            }
            catch {
                Write-Host "   ⚠️  Failed to load event log issues: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
    }
    
    Write-Host "`nHealth Data Summary:" -ForegroundColor Cyan
    Write-Host "   CA Servers: $($allHealthSummary.Count)" -ForegroundColor White
    Write-Host "   CRL Health Entries: $($allCRLHealth.Count)" -ForegroundColor White
    Write-Host "   AIA Health Entries: $($allAIAHealth.Count)" -ForegroundColor White
    Write-Host "   Template Health Entries: $($allTemplateHealth.Count)" -ForegroundColor White
    Write-Host "   Event Log Issues: $($allEventLogIssues.Count)" -ForegroundColor White
}

# ============================================================================
# CREATE EXCEL WORKBOOK
# ============================================================================

Write-Host "`n$Separator" -ForegroundColor Cyan
Write-Host "Creating Excel Workbook" -ForegroundColor Cyan
Write-Host $Separator -ForegroundColor Cyan

try {
    # Remove existing file if present
    if (Test-Path $OutputFile) {
        Remove-Item $OutputFile -Force
    }
    
    # Create Excel package
    $excelParams = @{
        Path = $OutputFile
        AutoSize = $true
        FreezeTopRow = $true
        BoldTopRow = $true
    }
    
    # Overview/Summary worksheet
    Write-Host "`nCreating worksheet: Overview" -ForegroundColor Cyan
    $overview = [PSCustomObject]@{
        OrganizationName = $OrganizationName
        ReportGeneratedDate = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        TotalCAServers = $latestAssessments.Count
        TotalCertificates = $allCertificates.Count
        TotalTemplates = ($allTemplates | Select-Object -Unique DisplayName).Count
        AssessmentDataSource = $AssessmentPath
        HealthDataSource = if ($healthPathExists) { $HealthPath } else { "N/A" }
    }
    $overview | Export-Excel @excelParams -WorksheetName "Overview"
    
    # CA Summary worksheet
    if ($caSummary.Count -gt 0) {
        Write-Host "Creating worksheet: CA Summary ($($caSummary.Count) entries)" -ForegroundColor Cyan
        $caSummary | Export-Excel @excelParams -WorksheetName "CA Summary"
    }
    
    # Issued Certificates worksheet
    if ($allCertificates.Count -gt 0) {
        Write-Host "Creating worksheet: Issued Certificates ($($allCertificates.Count) entries)" -ForegroundColor Cyan
        $allCertificates | Export-Excel @excelParams -WorksheetName "Issued Certificates"
    }
    
    # Certificate Templates worksheet
    if ($allTemplates.Count -gt 0) {
        Write-Host "Creating worksheet: Certificate Templates ($($allTemplates.Count) entries)" -ForegroundColor Cyan
        $allTemplates | Export-Excel @excelParams -WorksheetName "Certificate Templates"
    }
    
    # Template Permissions worksheet
    if ($allPermissions.Count -gt 0) {
        Write-Host "Creating worksheet: Template Permissions ($($allPermissions.Count) entries)" -ForegroundColor Cyan
        $allPermissions | Export-Excel @excelParams -WorksheetName "Template Permissions"
    }
    
    # Health Summary worksheet
    if ($allHealthSummary.Count -gt 0) {
        Write-Host "Creating worksheet: Health Summary ($($allHealthSummary.Count) entries)" -ForegroundColor Cyan
        $allHealthSummary | Export-Excel @excelParams -WorksheetName "Health Summary"
    }
    
    # CRL Health worksheet
    if ($allCRLHealth.Count -gt 0) {
        Write-Host "Creating worksheet: CRL Health ($($allCRLHealth.Count) entries)" -ForegroundColor Cyan
        $allCRLHealth | Export-Excel @excelParams -WorksheetName "CRL Health"
    }
    
    # AIA Health worksheet
    if ($allAIAHealth.Count -gt 0) {
        Write-Host "Creating worksheet: AIA Health ($($allAIAHealth.Count) entries)" -ForegroundColor Cyan
        $allAIAHealth | Export-Excel @excelParams -WorksheetName "AIA Health"
    }
    
    # Template Health worksheet
    if ($allTemplateHealth.Count -gt 0) {
        Write-Host "Creating worksheet: Template Health ($($allTemplateHealth.Count) entries)" -ForegroundColor Cyan
        $allTemplateHealth | Export-Excel @excelParams -WorksheetName "Template Health"
    }
    
    # Event Log Issues worksheet
    if ($allEventLogIssues.Count -gt 0) {
        Write-Host "Creating worksheet: Event Log Issues ($($allEventLogIssues.Count) entries)" -ForegroundColor Cyan
        $allEventLogIssues | Export-Excel @excelParams -WorksheetName "Event Log Issues"
    }
    
    Write-Host "`n✅ Excel workbook created successfully" -ForegroundColor Green
}
catch {
    Write-Host "`n❌ Failed to create Excel workbook: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# ============================================================================
# COMPLETION SUMMARY
# ============================================================================

$EndTime = Get-Date
$Duration = $EndTime - $StartTime

Write-Host "`n$Separator" -ForegroundColor Cyan
Write-Host "CONSOLIDATION COMPLETED" -ForegroundColor Green
Write-Host $Separator -ForegroundColor Cyan
Write-Host "Duration: $($Duration.ToString('mm\:ss'))" -ForegroundColor White
Write-Host "`nConsolidated Report: $OutputFile" -ForegroundColor Green
Write-Host "`nWorksheets Created:" -ForegroundColor Cyan
Write-Host "   • Overview" -ForegroundColor White
if ($caSummary.Count -gt 0) { Write-Host "   • CA Summary" -ForegroundColor White }
if ($allCertificates.Count -gt 0) { Write-Host "   • Issued Certificates" -ForegroundColor White }
if ($allTemplates.Count -gt 0) { Write-Host "   • Certificate Templates" -ForegroundColor White }
if ($allPermissions.Count -gt 0) { Write-Host "   • Template Permissions" -ForegroundColor White }
if ($allHealthSummary.Count -gt 0) { Write-Host "   • Health Summary" -ForegroundColor White }
if ($allCRLHealth.Count -gt 0) { Write-Host "   • CRL Health" -ForegroundColor White }
if ($allAIAHealth.Count -gt 0) { Write-Host "   • AIA Health" -ForegroundColor White }
if ($allTemplateHealth.Count -gt 0) { Write-Host "   • Template Health" -ForegroundColor White }
if ($allEventLogIssues.Count -gt 0) { Write-Host "   • Event Log Issues" -ForegroundColor White }
Write-Host $Separator -ForegroundColor Cyan
